### ISSUE TITLE
Error on Tshock build #501

### ISSUE THREAD

**Issue by SmallSansSerif** [CoderCow/Protector-Plugin#29]
http://pastebin.com/Rj7izamm

Is this error due to a Tshock API mismatch? Using your latest from a few hours ago build against 1.3.0.6

http://direct.tshock.co:8085/browse/TERRA-TSHOCK-501

**Comment by CoderCow** [comment]
The problem is that they are changing method signatures in the Terraria Server code. Even if those are only optional parameters, the signature is still different, thus the method can not be found anymore by the referencing assembly (by the plugin). So the plugin must be rebuild in order to match the new method signatures.

They would usually probably API tick as they do changes like this, so that it is clear that the plugins at least need to be rebuild in order to work. But of course, you can't blame them for not ticking the API version as they aren't publishing official releases. 

So it's actually your bad if you take the most recent version from their repository and think that the plugins would be compatible. Either take official releases only, which make (by the API version) clear whether plugins are compatible or not, or build it together with all plugins you're using in your server to ensure compatibility by yourself.

**Comment by SmallSansSerif** [comment]
Thanks for the good explanation. I'm sticking with my working version for now.
